apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: pruferco-http-gateway
  labels:
    {{- include "pruferco.labels" . | nindent 4 }}
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "prufer.co"
    - "www.prufer.co"
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: prufer-co-certificate
    hosts:
    - "prufer.co"
    - "www.prufer.co"
