export const Projects = [
    {
        id: "nyc",
        title: "East Coast Shots",
        alias: "nyc",
        category: "photo",
        yFinished: 2015,
        mFinished: 8,
        yUploaded: 2022,
        mUploaded: 10,
        reach: 20,
        reachType: "people",
        previewImages: ["./images/nyc/1s.jpg","./images/nyc/2s.jpg","./images/nyc/18s.jpg","./images/nyc/4s.jpg"],
        hoverVideo: false,
        previewCluster: "imgGrid2",
        description1: "During the summer of 2015, i spent 6 weeks visiting my uncle in Manhattan. Days and evenings I was wondering around the city on my own, taking pictures as I went - but mostly trying to hide my chunky DSLR camera to seem more local. I'd say this holiday was transformative for me, I returned more mature and independent, having left my home bubble for the first time.",
        images: ["./images/nyc/1.jpg","./images/nyc/2.jpg","./images/nyc/3.jpg","./images/nyc/4.jpg","./images/nyc/5.jpg","./images/nyc/6.jpg","./images/nyc/7.jpg","./images/nyc/8.jpg","./images/nyc/9.jpg","./images/nyc/10.jpg","./images/nyc/11.jpg","./images/nyc/12.jpg","./images/nyc/13.jpg","./images/nyc/14.jpg","./images/nyc/15.jpg","./images/nyc/16.jpg","./images/nyc/17.jpg","./images/nyc/18.jpg","./images/nyc/19.jpg","./images/nyc/20.jpg","./images/nyc/21.jpg","./images/nyc/22.jpg","./images/nyc/23.jpg","./images/nyc/24.jpg","./images/nyc/25.jpg","./images/nyc/26.jpg","./images/nyc/27.jpg","./images/nyc/28.jpg","./images/nyc/29.jpg","./images/nyc/30.jpg","./images/nyc/31.jpg","./images/nyc/32.jpg","./images/nyc/33.jpg","./images/nyc/34.jpg","./images/nyc/35.jpg","./images/nyc/36.jpg","./images/nyc/37.jpg","./images/nyc/38.jpg","./images/nyc/39.jpg","./images/nyc/40.jpg","./images/nyc/41.jpg","./images/nyc/42.jpg","./images/nyc/43.jpg","./images/nyc/44.jpg","./images/nyc/45.jpg","./images/nyc/46.jpg","./images/nyc/47.jpg","./images/nyc/48.jpg","./images/nyc/49.jpg","./images/nyc/50.jpg","./images/nyc/51.jpg","./images/nyc/52.jpg","./images/nyc/53.jpg","./images/nyc/54.jpg","./images/nyc/55.jpg","./images/nyc/56.jpg","./images/nyc/57.jpg","./images/nyc/58.jpg","./images/nyc/59.jpg"],
        collaborators: false,
    },
    {
        id: 2,
        title: "Sydenham Hill Autumn, 2019",
        alias: "syd",
        category: "photo",
        dateFinished: "2019-11-10",
        dateUploaded: "2022-11-12",
        reach: 200,
        reachType: "people",
        previewImages: ["./images/syd/1s.jpg","./images/syd/2s.jpg","./images/syd/3s.jpg","./images/syd/4s.jpg","./images/syd/5s.jpg","./images/syd/6s.jpg"],
        hoverVideo: false,
        previewCluster: "imgGrid3",
        description: "During the summer of 2015, i spent 6 weeks visiting my uncle in Manhattan. Days and evenings I was wondering around the city on my own, taking pictures as I went - but mostly trying to hide my chunky DSLR camera to seem more local. I'd say this holiday was transformative for me, I returned more mature and independent, having left my home bubble for the first time.",
        images: ["./images/nyc/1.jpg","./images/nyc/2.jpg","./images/nyc/3.jpg","./images/nyc/4.jpg","./images/nyc/5.jpg","./images/nyc/6.jpg","./images/nyc/7.jpg","./images/nyc/8.jpg","./images/nyc/9.jpg","./images/nyc/10.jpg","./images/nyc/11.jpg","./images/nyc/12.jpg","./images/nyc/13.jpg","./images/nyc/14.jpg","./images/nyc/15.jpg","./images/nyc/16.jpg","./images/nyc/17.jpg","./images/nyc/18.jpg","./images/nyc/19.jpg","./images/nyc/20.jpg","./images/nyc/21.jpg","./images/nyc/22.jpg","./images/nyc/23.jpg","./images/nyc/24.jpg","./images/nyc/25.jpg","./images/nyc/26.jpg","./images/nyc/27.jpg","./images/nyc/28.jpg","./images/nyc/29.jpg","./images/nyc/30.jpg","./images/nyc/31.jpg","./images/nyc/32.jpg","./images/nyc/33.jpg","./images/nyc/34.jpg","./images/nyc/35.jpg","./images/nyc/36.jpg","./images/nyc/37.jpg","./images/nyc/38.jpg","./images/nyc/39.jpg","./images/nyc/40.jpg","./images/nyc/41.jpg","./images/nyc/42.jpg","./images/nyc/43.jpg","./images/nyc/44.jpg","./images/nyc/45.jpg","./images/nyc/46.jpg","./images/nyc/47.jpg","./images/nyc/48.jpg","./images/nyc/49.jpg","./images/nyc/50.jpg","./images/nyc/51.jpg","./images/nyc/52.jpg","./images/nyc/53.jpg","./images/nyc/54.jpg","./images/nyc/55.jpg","./images/nyc/56.jpg","./images/nyc/57.jpg","./images/nyc/58.jpg","./images/nyc/59.jpg"],
        collaborators: false,
    },
    {
        id: 10,
        title: "Tate Onda (British hip hop project)",
        alias: "tate",
        category: "music",
        dateFinished: "today",
        dateUploaded: "2022-10-22",
        reach: 10,
        reachType: "plays",
        previewImages: ["./images/JAKOB-1.jpg"],
        hoverVideo: false,
        previewCluster: "imgGrid1",
        description: "During the summer of 2015, i spent 6 weeks visiting my uncle in Manhattan. Days and evenings I was wondering around the city on my own, taking pictures as I went - but mostly trying to hide my chunky DSLR camera to seem more local. I'd say this holiday was transformative for me, I returned more mature and independent, having left my home bubble for the first time.",
        images: ["./images/JAKOB-1.jpg"],
        collaborators: false,
    },
    {
        id: 11,
        title: "Jakob Prufer (German hip hop project)",
        alias: "jp",
        category: "music",
        dateFinished: "today",
        dateUploaded: "2022-11-17",
        reach: 120000,
        reachType: "plays",
        previewImages: ["./images/21e.JPEG"],
        hoverVideo: false,
        previewCluster: "imgGrid1",
        description: "During the summer of 2015, i spent 6 weeks visiting my uncle in Manhattan. Days and evenings I was wondering around the city on my own, taking pictures as I went - but mostly trying to hide my chunky DSLR camera to seem more local. I'd say this holiday was transformative for me, I returned more mature and independent, having left my home bubble for the first time.",
        images: ["./images/21e.JPEG"],
        collaborators: false,
    },
]