name: test
on: [push, pull_request]

jobs:
  lint-helm-chart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Lint helm chart
        run: helm lint deployment/helm/pruferco

  build-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Build website
        run: |
          yarn install
          yarn build

      - name: Lint website
        run: yarn run lint

  build-containers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - id: query
        uses: romnn/query-git-action@main

      - name: Build container
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64
          push: false
          build-args: |
            version=${{ steps.query.outputs.semver_version }}
          tags: |
            pruferco:latest
