name: test
on: [push, pull_request]

jobs:
  lint-helm-chart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Lint helm chart
        run: helm lint deployment/helm/pruferco
